#' @title RunTcrClustering
#' @description Cluster TCR distance assays in a single Seurat/tcr object and write compact tables to disk.
#' This function expects the user to have already subsetted their data (no grouping column).
#' It supports single-chain assays and multi-chain (paired) assays. For single-chain assays the
#' output table has columns: chain, v_gene, j_gene, CDR3, Cluster, Cluster_Size_Threshold, Clustering_Method, ...
#' For paired assays (two chains) the output table is written with columns: chain_1, v_gene_1, j_gene_1, CDR3_1, chain_2, v_gene_2, j_gene_2, CDR3_2, Cluster, ...
#'
#' @param seuratObj_TCR Seurat object produced by RunTcrdist3 (contains distance assays and metadata). If NULL, provide `metadata` and `distance_matrices` instead.
#' @param chainsToCluster Character vector of assay names to cluster. If NULL, all assays in `seuratObj_TCR` will be processed.
#' @param clusteringMethod "DIANA" or "Leiden". Default = "DIANA". If "Leiden", ClusterTcrs() is used.
#' @param dianaHeight DIANA cut height (used when clusteringMethod == "DIANA"). Default = 20.
#' @param clusterSizeThreshold Minimum cluster size to keep (clusters below set to 0). Default = 2.
#' @param verbose Logical. Print progress. Default = TRUE.
#' @return A seurat_TCR object with the cluster assignments stored in the metadata
#' @export
RunTcrClustering <- function(seuratObj_TCR = NULL,
                             chainsToCluster = NULL,
                             clusteringMethod = "DIANA",
                             dianaHeight = 20,
                             clusterSizeThreshold = 2,
                             verbose = TRUE
                           ) {

  if (! 'TCR_Distances' %in% names(seuratObj_TCR@misc)) {
    stop('This should be a seuratObject generated by tcrClustR. It will contain a list of distance matrices under seuratObj_TCR@misc$TCR_Distances')
  }

  if (is.null(chainsToCluster)) {
    chainsToCluster <- c('TRA', 'TRB', 'TRG', 'TRD', .get_chain_field_prefix(c('TRA', 'TRB')), .get_chain_field_prefix(c('TRG', 'TRD')))
  }

  assayNames <- paste0(chainsToCluster, c("_fl", "_cdr3"))
  assayNames <- intersect(assayNames, names(seuratObj_TCR@misc$TCR_Distances))
  if (length(assayNames) == 0)
    stop("No assays found to cluster. Provide valid assay names or a seuratObj_TCR with assays.")

  for (assayName in assayNames) {
    if (verbose) message("Processing assay: ", assayName)

    dist_matrix <- Seurat::GetAssayData(seuratObj_TCR@misc$TCR_Distances[[assayName]], layer = 'counts')
    if (is.null(dist_matrix)) {
      stop(paste0('Expected the distance matrix to be stored under seuratObj_TCR@misc$TCR_Distances$', assayName))
    }
    
    # check if matrix is too small or empty
    if (nrow(dist_matrix) < 2 || ncol(dist_matrix) < 2) {
      warning("Skipping assay ", assayName, ": distance matrix too small (", nrow(dist_matrix), "x", ncol(dist_matrix), ")")
      next
    }

    # check if matrix is too small or empty
    if (nrow(dist_matrix) != ncol(dist_matrix)) {
      stop("Expected distance matrix tobe square for assay ", assayName, ", was: ", nrow(dist_matrix), "x", ncol(dist_matrix))
    }

    # clustering
    if (clusteringMethod == "DIANA") {
      clustering_result <- .DianaClustering(dist_matrix, cutHeight = dianaHeight, verbose = verbose)
      cluster_assignments <- clustering_result$clustering
    } else if (clusteringMethod == "Leiden") {
      # TODO: could restore this?
      stop("Leiden is not currently supported")
    } else {
      stop("Unsupported clusteringMethod: ", clusteringMethod)
    }

    # apply cluster size threshold
    filtered_assignments <- .ThresholdClustersBySize(cluster_assignments, minClusterSize = clusterSizeThreshold, verbose = verbose)

    # Now store back into the seurat object, top-level and assay-level:
    chainId <- paste0(head(unlist(strsplit(assayName, split = '_')), -1), collapse = '_')
    cloneIdxCol <- paste0(chainId, '_CloneIdx')
    clusterIdxCol <- paste0(chainId, '_ClusterIdx')
    toAdd <- data.frame(CloneIdx = names(filtered_assignments), ClusterIdx = unname(filtered_assignments))
    names(toAdd) <- c(cloneIdxCol, clusterIdxCol)

    # First top-level seurat meta.data
    if (! cloneIdxCol %in% names(seuratObj_TCR@meta.data)) {
      stop(paste0('Missing field in seurat metadata: ', cloneIdxCol))
    }

    if ( clusterIdxCol %in% names(seuratObj_TCR@meta.data)) {
      message(paste0('Replacing existing clustering data: ', clusterIdxCol))
      seuratObj_TCR[[clusterIdxCol]] <- NULL
    }

    toAddMeta <- seuratObj_TCR@meta.data[, cloneIdxCol, drop = FALSE] |>
      tibble::rownames_to_column('RowNames_') |>
      dplyr::left_join(toAdd, by = cloneIdxCol) |>
      tibble::column_to_rownames('RowNames_')

    if (any(rownames(toAddMeta) != rownames(seuratObj_TCR@meta.data))) {
      stop('Expected rownames to match after left_join of seurat metadata')
    }

    seuratObj_TCR <- Seurat::AddMetaData(seuratObj_TCR, toAddMeta)
    rm(toAddMeta)

    # Then the distance matrix:
    ad <- seuratObj_TCR@misc$TCR_Distances[[assayName]]
    # Difference behavior for Seurat4/5 assays:
    if ('meta.features' %in% methods::slotNames(ad)) {
      if ( clusterIdxCol %in% names(ad@meta.features)) {
        message(paste0('Replacing existing clustering results for assay: ', assayName))
        ad@meta.features[[clusterIdxCol]] <- NULL
      }
    } else {
      if ( clusterIdxCol %in% names(ad@meta.data)) {
        message(paste0('Replacing existing clustering results for assay: ', assayName))
        ad@meta.data[[clusterIdxCol]] <- NULL
      }
    }

    toAddAssay <- data.frame(CloneIdx = rownames(ad), RowNames = rownames(ad)) |>
      dplyr::left_join(toAdd, by = c('CloneIdx' = cloneIdxCol)) |>
      tibble::column_to_rownames('RowNames')
    toAddAssay$CloneIdx <- NULL

    if (any(rownames(toAddAssay) != rownames(ad))) {
      stop('Expected rownames to match after left_join of distances assay')
    }

    seuratObj_TCR@misc$TCR_Distances[[assayName]] <- Seurat::AddMetaData(ad, toAddAssay)
    rm(toAddAssay)
  }

  if (length(names(seuratObj_TCR@reductions)) > 0) {
    print(Seurat::DimPlot(
      seuratObj_TCR,
      reduction = "umap",
      group.by = 'TRB_ClusterIdx',
      label = TRUE,
      pt.size = 1
    ))
  }

  return(seuratObj_TCR)
}

