name: Build Docker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 11 * *'  #11th of the month at 5PM
    - cron: '0 17 26 * *'  #26th of the month at 5PM
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  generate:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ghcr.io/gwmcelfresh/tcrclustr
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "GH_PAT=${{ secrets.GITHUB_TOKEN }}"
          push: true
          tags: |
            ghcr.io/gwmcelfresh/tcrclustr:latest
            ghcr.io/gwmcelfresh/tcrclustr:nightly
