on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
  pull_request:
  schedule:
    - cron: '0 17 11 * *'  #11th of the month at 5PM
    - cron: '0 17 26 * *'  #26th of the month at 5PM

name: R Build and Checks

jobs:
  R-CMD-check:
    runs-on: ubuntu-${{ matrix.config.os }}

    name: ubuntu-${{ matrix.config.os }} (${{ matrix.config.r }} / ${{ matrix.config.bioc }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: 24.04, r: '4.4', bioc: '3.20', pkgdown: "true" }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: bimberlabinternal/DevOps/githubActions/r-gh-setup@master
        with:
          r_version: ${{ matrix.config.r }}
          bioc_version: ${{ matrix.config.bioc }}
          cache_version: ${{ secrets.CACHE_VERSION }}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Install package-specific Python dependencies
        if: runner.os != 'Windows'
        run: |
          python3 -m pip install --user scikit-learn tqdm sympy pyyaml rpy2

      - name: Debug Python environment
        if: runner.os != 'Windows'
        run: |
          python3 --version
          python3 -m pip --version
          python3 -m pip list
          python3 -c "import pandas; print(pandas.__version__)"
          python3 -c "import tcrdist3; print(tcrdist3.__path__)"
          python3 -c "import tcrdist; print(tcrdist.__path__)"
          python3 -c "import tcrdist;import os;import sys;os.path.abspath(sys.modules[TCRrep.__module__].__file__)"
          python3 -c "import tcrdist; print(tcrdist.__dict__)"
        shell: bash

      - name: Test Python script standalone
        if: runner.os != 'Windows'
        run: |
          python3 inst/scripts/PullTcrdist3Db.py

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual")'
        env:
          _R_CHECK_CRAN_INCOMING_: false

      - name: Install package
        if: github.ref == 'refs/heads/main' && matrix.config.pkgdown == 'true'
        run: R CMD INSTALL .

      - name: Deploy package
        if: github.ref == 'refs/heads/main' && matrix.config.pkgdown == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, clean = TRUE)'
